// ============================================================
// Lightweight server-side allowlist sanitizer for AI-generated blog HTML.
// The content is admin-authored/reviewed (generated by our own Groq call),
// so this is defense-in-depth — it strips scripts, event handlers, and
// dangerous URLs, and keeps only a small set of formatting tags.
// ============================================================

const ALLOWED_TAGS = new Set([
  'h2', 'h3', 'h4', 'p', 'ul', 'ol', 'li', 'strong', 'em', 'b', 'i', 'a', 'blockquote', 'br', 'hr',
]);

export function sanitizeBlogHtml(html: string): string {
  let out = String(html ?? '');

  // Drop dangerous elements (and their content for script/style).
  out = out.replace(/<script[\s\S]*?<\/script>/gi, '');
  out = out.replace(/<style[\s\S]*?<\/style>/gi, '');
  out = out.replace(/<\/?(iframe|object|embed|form|input|button|link|meta|svg|math|base|title)[^>]*>/gi, '');

  // Strip inline event handlers (onclick=, onerror=, ...).
  out = out.replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, '');

  // Neutralize javascript:/data: protocols in href/src.
  out = out.replace(/(href|src)\s*=\s*("|')?\s*(javascript|data):[^"'>\s]*/gi, '$1="#"');

  // Remove any tag not in the allowlist, keeping inner text.
  out = out.replace(/<\/?([a-zA-Z0-9]+)([^>]*)>/g, (match, tag: string) =>
    ALLOWED_TAGS.has(tag.toLowerCase()) ? match : '',
  );

  // Harden external links: add rel/target when linking off-site.
  out = out.replace(/<a\s+([^>]*?)href\s*=\s*("|')(https?:\/\/[^"']+)\2([^>]*)>/gi, (_m, pre, q, url, post) => {
    const attrs = `${pre}href=${q}${url}${q}${post}`.replace(/\s*(target|rel)\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, '');
    return `<a ${attrs.trim()} target="_blank" rel="noopener noreferrer">`;
  });

  return out.trim();
}
